In [ ]:
#this is my first code 

In [6]:
#addition

a=2
b=3
c= a+b
c

5

In [20]:
#numbers: Integer
n_int = 2023
type(n_int)


int

In [10]:
n_float=9.8
type(n_float)

float

In [11]:
n_nan_float=nan
type(n_nan_float)

NameError: name 'nan' is not defined

In [22]:
a= 'Hello World' #alphanumeric 
type(a)

str

In [16]:
n1=4
n2=3
n3=4
n=n1+n2+n3



11

In [37]:
power=2**3 #power
power

8

In [27]:
e=""
type(e)

str

In [33]:
#string ops
a='pyhton'
len(a)

6

In [54]:
a='python'
a[0]
a[1]
a[2]
a[3]
a[4]
a[0:-2]

'pyth'

In [55]:
s1='I Love Python' #list
list(s1.split()) 

['I', 'Love', 'Python']

In [68]:
v= 'I', 'Love', 'Python' #for 1st and last words
v[0]+" "+v[2] 

'I Python'

In [ ]:
# ' '" " using quotes a.k.a doc string

In [4]:
s= "python"
s[-1]

'n'

In [ ]:
# CRUD Create, Retreive, Update, Delete


In [11]:
s= "python"
print(s.replace("python", "pythons")) #How to replace a string 

pythons


In [18]:
print(s.replace("pythons","pithins"))

python


In [19]:
s1="python"
print(s1.replace("python", "pythons"))

pythons


In [21]:
print(s1.replace(s1,"pithons"))

pithons


In [22]:
print(s1.replace(s1, "pithons"))

pithons


In [23]:
print(s1.replace(s1,"pmthons"))

pmthons


In [31]:
s="python"
s1=s.replace('python', 'python') #update and delete
print(s1)

python


In [ ]:
s="pyhton"
s1=s.delete()

In [32]:
n=3.14
str(n) # create :changing data type of a number 

'3.14'

In [ ]:
a= 'abcd'
b= 'abCd' #find function that will match a and b - questions
a==b   #usecasefold


In [ ]:
# python data types 

In [43]:
a = True
b= not a
c= a and b
d= a or b
e = b and b  #boolean algebra
print(c)
print(d)
print(e)

False
True
False


In [ ]:
#in, not in, is, not is ---- boolean 

In [45]:
v= None
type(v) #none data type

NoneType

In [46]:
v="hey"
type(v)

str

In [47]:
v=""
type(v)

str

In [49]:
v1= None  #none data type is different from empty string but output is given is same
v2=""
v1==v2

False

In [51]:
v3=" "
v3    #to find none or empty in a text ****

' '

In [ ]:
# list, tuple, set, dictionary

In [3]:
list=["Apple","Banana","Apple","Cherry"] #list - Lists are used to store multiple items in a single variable,square brackets,List items are ordered, changeable, and allow duplicate values,A list can contain different data types.
print(list)

['Apple', 'Banana', 'Apple', 'Cherry']


In [5]:
l1= [1,1.1,2,2.1]
print(l1)

[1, 1.1, 2, 2.1]


In [6]:
type(l1)

list

In [7]:
l2=["a","b","c"]
type(l2)

list

In [8]:
l3=["a", " ", "c"]
type(l3)

list

In [9]:
l3[1]

' '

In [13]:
l4=[True, False, and, or, not] #and, not,or they are itself are function and also are boolean that's why error and only true and false are boolean
type(l4)

SyntaxError: invalid syntax (3732817284.py, line 1)

In [17]:
l4=[None,None]
type(l4)

list

In [18]:
l5=[None, "a", True, 1, 1.1, " "] #mix of all the data types #list is independent of data type
type(l5) 

list

In [20]:
l6=[ ] #empty list is level 0 list 
type(l6)

list

In [34]:
l7=[[1,3],[2,4]] #list of list is level 3
type(l7)
l7[1][1] #to get inner list from the list of list 

4

In [23]:
l8=[[1],[1,"a", 1.1],[1,2],[2,3,4,4]]
type(l8)

list

In [38]:
l9=((1,"a", 1.1," ", None, True)) #tuple
type(l9) 


tuple

In [42]:
l10=((1,2),("a","b")) #to get inner tuple from tuple of tuple
type(l10)
l10[1][0]

'a'

In [45]:
l11=[(1,2,), ("a,","b")] #list of tuple - yes, retrieve is also can be done.
type(l11)
l11[0]

(1, 2)

In [48]:
l12=([1,2],["a","b"])
type(l12)
l12[0][1]

2

In [8]:
original_tuple = (1, 2, 3, 4, 5)
updated_list = list(original_tuple)    #how to convert and update tuple in list and vice versa
updated_list[2] = 10
updated_list[4]= 15
original_tuple = tuple(updated_list)

print(original_tuple)

(1, 2, 10, 4, 15)


In [ ]:
#dataframe modelling 7th Aug '23

In [4]:
r=range(9) #range

list(r)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
r2=range(0,9,1) #range(start/stop/increment)
r2
list(r2)

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
r==r2

True

In [9]:
r3=range(5,-1,-1) #to get 0 use -1
list(r3)

[5, 4, 3, 2, 1, 0]

In [10]:
s={0,1,1,2,3,5,8} #set will give you unique values 
s

{0, 1, 2, 3, 5, 8}

In [11]:
s1={"a","n","a","c","o","n","d","a"}
s1

{'a', 'c', 'd', 'n', 'o'}

In [12]:
s4={1,2,3,4}
s5={'a','b',1,2,3}   #union and intersection #set is complex data type
s6={7,8,9}
set.union(s4,s5,s6)

{1, 2, 3, 4, 7, 8, 9, 'a', 'b'}

In [14]:
set.intersection(s4,s5)

{1, 2, 3}

In [15]:
set.intersection(s4,s5,s6)

set()

In [17]:
s7=(1,2,3,4)
list(s7)

[1, 2, 3, 4]

In [19]:
s4[0] #elements of set are not fetched, to do convert into list

TypeError: 'set' object is not subscriptable

In [ ]:
#dictionary


In [21]:
d={"045004":"Aditya", "045009": "Ansh"}
type(d)

dict

In [23]:
dict.keys(d)

dict_keys(['045004', '045008'])

In [26]:
dict.values(d)

dict_values(['Aditya', 'Ansh'])

In [28]:
d1={"Aditya":"1", "Ansh":"2"} #reverse
type(d1) 

dict

In [29]:
dict.keys(d1)

dict_keys(['Aditya', 'Ansh'])

In [30]:
dict.values(d1)

dict_values(['1', '2'])

In [31]:
d3={"0":"P","1":"Y","1":"T","2":"H","3":"O","5":"N"} #keys should be unique
type(d3)

dict

In [32]:
dict.keys(d3)

dict_keys(['0', '1', '2', '3', '5'])

In [34]:
dict.values(d3)

dict_values(['P', 'T', 'H', 'O', 'N'])

In [35]:
d4={"a":"8","n":"1","a":"2","c":"5","o":"5","n":"9","d":"6","a":"4","s":"2"}
type(d4)

dict

In [36]:
dict.keys(d4) #key is unique and check whether it can take float

dict_keys(['a', 'n', 'c', 'o', 'd', 's'])

In [37]:
dict.values(d4) 

dict_values(['4', '9', '5', '5', '6', '2'])

In [39]:
d5={"1":"[b,c,d]","2":"[e,f,g]"}
d5

{'1': '[b,c,d]', '2': '[e,f,g]'}

In [48]:
d5.get(2) #fetch the value of the key 

In [49]:
count = 1
while count <= 5:
    print("Current count:", count)
    count += 1


Current count: 1
Current count: 2
Current count: 3
Current count: 4
Current count: 5


In [ ]:
#large number and check even numbers

In [54]:
count_even = 0
for num in range(1, 12004):
    if num % 2 == 0:
        count_even += 1
print("The count of even numbers from 1 to 12004 is:", count_even)



The count of even numbers from 1 to 12004 is: 6001


In [55]:
count_odd = 1
for num in range(1, 12004):
    if num % 2 != 0:
        count_odd += 1
print("The count of odd numbers from 1 to 12004 is:", count_odd)


The count of odd numbers from 1 to 12004 is: 6003


In [ ]:
#8th aug 23

In [7]:
v=3
while v >= 0:
 v
 v= v-1
print(v)


-1


In [ ]:
#if then else with for

In [41]:
word = "anaconda"
vowels = []
consonants = []

for letter in word:
    if letter.lower() in 'aeiou':
        vowels.append(letter)
    else:
        consonants.append(letter)

print("Vowels:", vowels)
print("Consonants:", consonants)



Vowels: ['a', 'a', 'o', 'a']
Consonants: ['n', 'c', 'n', 'd']


In [ ]:
#mixed list , number bool none string atleast 2

In [ ]:
ml=[1,2,1.1,2.1,a,b,abc12," ", True,False,None] #homogenize
Number=[]
String=[]
Boo=[]
Empty=[]

In [44]:
mixed_list = [42, "Hello", 3.14, True, ["apple", 5]]

int_list = []
str_list = []
float_list = []
bool_list = []
nested_list = []

for item in mixed_list:
    if isinstance(item, int):
        int_list.append(item)
    elif isinstance(item, str):
        str_list.append(item)
    elif isinstance(item, float):
        float_list.append(item)
    elif isinstance(item, bool):
        bool_list.append(item)
    elif isinstance(item, list):
        nested_list.append(item)

print("Mixed List:", mixed_list)
print("\nSeparated Lists:")
print("Integer List:", int_list)
print("String List:", str_list)
print("Float List:", float_list)
print("Boolean List:", bool_list)
print("Nested List:", nested_list)


Mixed List: [42, 'Hello', 3.14, True, ['apple', 5]]

Separated Lists:
Integer List: [42, True]
String List: ['Hello']
Float List: [3.14]
Boolean List: []
Nested List: [['apple', 5]]


In [47]:
mixed_list = [42, "Hello", 3.14, True,None]
 
int_list = [] numlist string list boolean #exam
str_list = []
float_list = []
bool_list = []
nested_list = []

for item in mixed_list:
    if type(item) == int:
        int_list.append(item)
    elif type(item) == str:
        str_list.append(item)
    elif type(item) == float:
        float_list.append(item)
    elif type(item) == bool:
        bool_list.append(item)
    elif type(item) == list:
        nested_list.append(item)

print("Mixed List:", mixed_list)
print("\nSeparated Lists:")
print("Integer List:", int_list)
print("String List:", str_list)
print("Float List:", float_list)
print("Boolean List:", bool_list)
print("Nested List:", nested_list)


Mixed List: [42, 'Hello', 3.14, True, None]

Separated Lists:
Integer List: [42]
String List: ['Hello']
Float List: [3.14]
Boolean List: [True]
Nested List: []


In [53]:
ml = [1,2.3,'a','pi',True, None, False, 9.8,0,-1,'xyz']
num_list=[]
str_list=[]
bool_list=[]
none_list=[]

for item in ml:
    if type(item)==int:
        num_list.append(item)
    elif type(item)==str:
        str_list.append(item)
    elif type(item)==bool:
        bool_list.append(item)
    elif type(item)== None:
        none_list.append(item) 
        
        
        

print("num",num_list)
print("str",num_list)
print("bool",num_list)
print("none",num_list)


num [1, 0, -1]
str [1, 0, -1]
bool [1, 0, -1]
none [1, 0, -1]


In [ ]:
def my=(v1,v2)
a=v1+v2
print(a)

In [ ]:
my(1,2)

In [ ]:
#10th august '23

In [ ]:
#write a code which will  using user input randon library randonly generate a series of 100 nos between 0 and 1 and segregate based on if it falls 0-0.25 it will go to loweer quartile , 025

In [1]:
import random

def categorize_number(number):
    if number <= 0.25:
        return "Lower Quartile"
    elif number <= 0.5:
        return "LUv"
    else:
        return "Other"

# Generate a series of 100 random numbers between 0 and 1
numbers = [random.random() for _ in range(100)]

# Categorize and store the numbers based on the defined conditions
lower_quartile = []
luv = []
other = []

for number in numbers:
    category = categorize_number(number)
    if category == "Lower Quartile":
        lower_quartile.append(number)
    elif category == "LUv":
        luv.append(number)
    else:
        other.append(number)

# Print the segregated results
print("Lower Quartile:", lower_quartile)
print("LUv:", luv)
print("Other:", other)


Lower Quartile: [0.04965546340684224, 0.21716742158268265, 0.16494766072029865, 0.2188066200794636, 0.23035914773106025, 0.05147704969117006, 0.247710707346677, 0.02840131903031118, 0.14098396488406817, 0.016341492409535197, 0.1796365856742942, 0.2417521225897562, 0.003788776357012358, 0.23038770369248196, 0.24199970284662342, 0.19605722539876946, 0.06320209989957637, 0.24987161671752356, 0.14748660044588657, 0.1935887841505851, 0.11213125429109172, 0.028750521471241686, 0.01427988803201552, 0.07477007578428374]
LUv: [0.4619270629447989, 0.4317294440456141, 0.4801154364730339, 0.35233719776102757, 0.33707424616750725, 0.35242776535561904, 0.39581846867454074, 0.3949691759787799, 0.43700735908508714, 0.3787853262071188, 0.2923298555041485, 0.30621716201187743, 0.3755166201585186, 0.37140585120847625, 0.48792100858145326, 0.2740369795404346, 0.3632868148659212, 0.43141112365275425, 0.28314013346330325, 0.39290786220064167, 0.29041897744887146, 0.312559331631585, 0.2723094517622092, 0.332

In [3]:
import numpy as np #for array and matrices #in python array are represented/arranged in column

# Create a 1D array using a list
my_array = np.array([1, 2, 3, 4, 5])

print(my_array)


[1 2 3 4 5]


In [4]:
import numpy as np

# Create a 1D array using a Python list #arrays are always arranged in column manner but in python it is shown in horizontal manner that is why python is not used in scientific computing. because it does not display in column 
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)

print(my_array)


[1 2 3 4 5]


In [5]:
import numpy as np

# Create a 2D array using a nested Python list
my_list_2d = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

my_array_2d = np.array(my_list_2d)

print(my_array_2d)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
 list2d= [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]

my_array_2d = np.array(list2d)

print(list2d)
a2.reshape(list2d)


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


NameError: name 'a2' is not defined

In [8]:
import numpy as np

# Create a 2D array
my_array_2d = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Reshape the 2D array to a 3D array with shape (2, 3, 1)
my_array_3d = np.reshape(my_array_2d, (my_array_2d.shape[0], my_array_2d.shape[1], 1))

print("Original 2D array:")
print(my_array_2d)
print("\nReshaped 3D array:")
print(my_array_3d)


Original 2D array:
[[1 2 3]
 [4 5 6]]

Reshaped 3D array:
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [10]:


# Create a 2D array
my_array_2d = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Method 1: Using the .T attribute
transposed_array_1 = my_array_2d.T

# Method 2: Using numpy.transpose()
transposed_array_2 = np.transpose(my_array_2d)

print("Original 2D array:")
print(my_array_2d)
print("\nTransposed using .T:")
print(transposed_array_1)
print("\nTransposed using numpy.transpose():")
print(transposed_array_2)


Original 2D array:
[[1 2 3]
 [4 5 6]]

Transposed using .T:
[[1 4]
 [2 5]
 [3 6]]

Transposed using numpy.transpose():
[[1 4]
 [2 5]
 [3 6]]


In [12]:

# Create a 1D array
my_array = np.array([5, 2, 9, 1, 7])

# Find the minimum and maximum values
minimum_value = np.min(my_array)
maximum_value = np.max(my_array)

print("Array:", my_array)
print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)


Array: [5 2 9 1 7]
Minimum value: 1
Maximum value: 9


In [15]:
import numpy as np

# Create a 2D array
my_array_2d = np.array([[1, 2, 3],
                        [4, 5, 6]])

# Row-wise minimum, maximum, and sum
row_min = np.min(my_array_2d, axis=1)
row_max = np.max(my_array_2d, axis=1)
row_sum = np.sum(my_array_2d, axis=1)

# Column-wise minimum, maximum, and sum
col_min = np.min(my_array_2d, axis=0)
col_max = np.max(my_array_2d, axis=0)
col_sum = np.sum(my_array_2d, axis=0)

print("Original 2D array:")
print(my_array_2d)
print("\nRow-wise minimum:", row_min)
print("Row-wise maximum:", row_max)
print("Row-wise sum:", row_sum)
print("\nColumn-wise minimum:", col_min)
print("Column-wise maximum:", col_max)
print("Column-wise sum:", col_sum)


Original 2D array:
[[1 2 3]
 [4 5 6]]

Row-wise minimum: [1 4]
Row-wise maximum: [3 6]
Row-wise sum: [ 6 15]

Column-wise minimum: [1 2 3]
Column-wise maximum: [4 5 6]
Column-wise sum: [5 7 9]


In [ ]:
x + 5y = 3 #[1,7] [5,3]
7x+ 3y = 5


In [ ]:
#pandas deals with df - data in table forms is df

In [16]:
import pandas as pd

In [17]:
# Create a dictionary with individual's information
person_info = {
    "name": "John Doe",
    "gender": "Male",
    "education": "Bachelor's Degree",
    "age": 30,
    "salary": 50000
}

# Print the dictionary
print(person_info)


{'name': 'John Doe', 'gender': 'Male', 'education': "Bachelor's Degree", 'age': 30, 'salary': 50000}


In [24]:
# Create a list of dictionaries, each representing an individual's information
people_info = [
    {
        "name": "John Doe",
        "gender": "Male",
        "education": "Bachelor's Degree",
        "age": 30,
        "salary": 50000
    },
    {
        "name": "Jane Smith",
        "gender": "Female",
        "education": "Master's Degree",
        "age": 28,
        "salary": 60000
    },
    {
        "name": "Alex Johnson",
        "gender": "Non-Binary",
        "education": "PhD",
        "age": 35,
        "salary": 75000
    }
]

# Print the list of dictionaries
for person in people_info:
    print(person)
df= pd.DataFrame(people_info)



{'name': 'John Doe', 'gender': 'Male', 'education': "Bachelor's Degree", 'age': 30, 'salary': 50000}
{'name': 'Jane Smith', 'gender': 'Female', 'education': "Master's Degree", 'age': 28, 'salary': 60000}
{'name': 'Alex Johnson', 'gender': 'Non-Binary', 'education': 'PhD', 'age': 35, 'salary': 75000}
